### ISSUE TITLE
FileNotFoundError on shellmarkets.log

### ISSUE THREAD

**Issue by pjespinosa** [croketillo/SHELLMARKETS#3]
### Symptom
`shellmarkets.log` not found when running a simple information request on ticker.

Error stack is:
```
Traceback (most recent call last):
  File "/root/shellmarkets/SHELLMARKETS/shellmarkets.py", line 331, in <module>
    log_search(information)
  File "/root/shellmarkets/SHELLMARKETS/shellmarkets.py", line 187, in log_search
    with open(log_file, "a", encoding="UTF-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/shellmarkets/shellmarkets.log'
```

### Environment
O`Reilly Python sandbox.

### Steps to reproduce the error
Run `python shellmarkets.py -t GOOG`.

**Comment by croketillo** [comment]
No puede crear el log porque ejecutas en un sandbox ¿correcto? y para hacer el log tiene que crear el archivo y leerlo… cosa que no puede hacer en un sandbox. Ejecuta en tu maquina Linux y no dara error

**Comment by croketillo** [comment]
Quizá podría intentar resolverlo metiendo esa parte en un try/except … creo que sería buena opción para controlar este error ya sea en un sandbox o por cualquier otro motivo. Lo mirare

**Comment by croketillo** [comment]
New update shellmarkets.py. "Control exception log".  Please check again. Thanks!
